// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3MHxEa173erDzzgjc0BShSeji4H6LRWk',
    appId: '1:718841604931:web:d1a81500c00eb56cbf5df6',
    messagingSenderId: '718841604931',
    projectId: 'biblioteca-flutter-4991e',
    authDomain: 'biblioteca-flutter-4991e.firebaseapp.com',
    storageBucket: 'biblioteca-flutter-4991e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8WlnmzmWAWg4SSRBd1hMmae_1o3xhGYQ',
    appId: '1:718841604931:android:637fe7a102f7f3c9bf5df6',
    messagingSenderId: '718841604931',
    projectId: 'biblioteca-flutter-4991e',
    storageBucket: 'biblioteca-flutter-4991e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgcuvs3kP_U7ofKmS33MNMj3_GNQiba1o',
    appId: '1:718841604931:ios:b68d374a46d663a6bf5df6',
    messagingSenderId: '718841604931',
    projectId: 'biblioteca-flutter-4991e',
    storageBucket: 'biblioteca-flutter-4991e.appspot.com',
    iosBundleId: 'com.example.bibliotecaFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgcuvs3kP_U7ofKmS33MNMj3_GNQiba1o',
    appId: '1:718841604931:ios:b68d374a46d663a6bf5df6',
    messagingSenderId: '718841604931',
    projectId: 'biblioteca-flutter-4991e',
    storageBucket: 'biblioteca-flutter-4991e.appspot.com',
    iosBundleId: 'com.example.bibliotecaFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3MHxEa173erDzzgjc0BShSeji4H6LRWk',
    appId: '1:718841604931:web:61f8c4fa3d17ed70bf5df6',
    messagingSenderId: '718841604931',
    projectId: 'biblioteca-flutter-4991e',
    authDomain: 'biblioteca-flutter-4991e.firebaseapp.com',
    storageBucket: 'biblioteca-flutter-4991e.appspot.com',
  );
}
